### ISSUE TITLE
Errors on every player login.

### ISSUE THREAD

**Issue by Zilacon** [rona-tombo/MCBansBungee#1]
I am getting this error whenever a player logs into my bungeecord. Any idea how to fix this?

![Screenshot_77](https://user-images.githubusercontent.com/3002248/56911195-35e3bc00-6a61-11e9-8379-4dd9112ba154.png)

**Comment by braddevans** [comment]
fixed that in my fork of the project
https://github.com/braddevans/MCBansBungee
required changing 
the pre login event to a postlogin event and 
changing this in the player listener on line 135
```
	public void onPlayerJoin(final PostLoginEvent event){
		final ProxiedPlayer player = ProxyServer.getInstance().getPlayer(event.getPlayer().getDisplayName());
```

**Comment by rona-tombo** [comment]
Thank you for telling me that!
I will release to fixing it!

**Comment by rona-tombo** [comment]
and may I use the icon of MCBans BungeeCord Edition in your repository?

**Comment by braddevans** [comment]
Yes
